---
- name: Configure Ansible Controller
  hosts: ansible_lab_controller
  tasks:
  - name: Ensure latest package versions
    become: yes
    ansible.builtin.package:
      name: 
      - ansible
      - git
      state: latest

- name: Universal host configuration
  hosts: ansible_lab_hosts
  vars:
    ansible_become: true
  roles:
  - role: ansible-hardening
    vars:
      stig_version: rhel7
      security_enable_pwquality_password_set: yes
      security_password_max_lifetime_days: 90
    tags: hardening
  tasks:
  - name: Add local hostname
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ansible_hostname}}$'
      line: "{{ansible_host}} {{ansible_hostname}}"
      state: present
    when: ansible_host is defined

- name: Configure Samba server
  hosts: ansible-lab-host2
  vars:
    ansible_become: true
  roles:
  - bertvv.samba

- name: Configure Samba client
  hosts: ansible-lab-host3
  vars:
    ansible_become: true
  tasks:
  - name: Install client deps
    package:
      name: cifs-utils
      state: latest
  - name: Create credential file
    template:
      src: ./files/.smbpasswd
      dest: /home/{{ admin_un }}/.smbpasswd
      owner: '{{ admin_un }}'
      group: '{{ admin_un }}'
      mode: '0600'
  - name: Add share mount
    mount:
      src: //10.1.2.5/testshare
      path: /mnt/smbshare
      fstype: cifs
      opts: credentials=/home/{{ admin_un }}/.smbpasswd
      state: mounted
  - name: Set mount as writeable
    file:
      path: /mnt/smbshare
      state: directory
      mode: '0777'