---
- name: Configure DNS server
  hosts: ansible-lab-host1
  vars:
    ansible_become: true
  roles:
  - role: bertvv.dnsmasq
    vars:
      dnsmasq_bogus_priv: true
      dnsmasq_domain: 'cool.name'
      dnsmasq_domain_needed: true
      dnsmasq_expand_hosts: true
      dnsmasq_upstream_servers:
      - 1.1.1.1
      - 1.0.0.1
      - 10.1.2.4
  tasks:
  - name: Install dnsmasq
    ansible.builtin.package:
      name: dnsmasq
      state: latest
  - name: Set host1 name
    lineinfile:
      path: /etc/hosts
      line: '10.1.2.4 c001-n@me1'
  - name: set host2 name
    lineinfile:
      path: /etc/hosts
      line: '10.1.2.5 c001-n@me2'
  - name: set host3 name
    lineinfile:
      path: /etc/hosts
      line: '10.1.2.6 c001-n@me3'
  
- name: Configure hosts to use local DNS
  hosts: all
  vars:
    ansible_become: true
  tasks:
  - name: Set resolv.conf nameserver
    lineinfile:
      path: /etc/resolv.conf
      regexp: '^nameserver'
      line: 'nameserver=10.1.2.4'

- name: Disable existing DNS
  hosts: new_group
  tasks:
  - name: stop system resolved  
    ansible.builtin.service:
      name: systemd-resolved
      enabled: no
      state: stopped

  - name: Set dnsmasq configuration file
    ansible.builtin.copy:
      src: ./files/dnsmasq.conf
      dest: /etc/dnsmasq.conf
      owner: root
      group: root
      mode: '0644'

  - name: Restart dnsmasq
    ansible.builtin.service:
      name: dnsmasq
      enabled: yes
      state: restarted